--* 사용자 정의 데이터 형식 별칭

-- ALTER
CREATE  TYPE VivNumber  
FROM NVARCHAR(10) NOT NULL ;

GO

USE PlayGround
GO



SELECT CURRENT_TIMESTAMP
-- GET_TRANSMISSION_STATUS

SELECT GETDATE()
SELECT GETUTCDATE()
SELECT @@CONNECTIONS
SELECT @@CPU_BUSY
SELECT @@DBTS
SELECT @@IDLE
SELECT @@IO_BUSY
SELECT @@MAX_CONNECTIONS
SELECT @@PACK_RECEIVED
SELECT @@PACK_SENT
SELECT @@PACKET_ERRORS
SELECT @@TIMETICKS
SELECT @@TOTAL_ERRORS
SELECT @@TOTAL_READ
SELECT @@TOTAL_WRITE
