--* Global Varable

select @@SERVERNAME as 'Server Name'
select @@VERSION
select @@MICROSOFTVERSION
select @@SERVICENAME

USE Movies;
SELECT * FROM Actor 
Select @@ROWCOUNT AS [행 갯수]

Select SERVERPROPERTY('MachineName') as 'MachineName'

select HOST_NAME() -- return nvarchar(128)

select @@ERROR

select @@TRANCOUNT

select @@DBTS

select @@IDENTITY

select @@SPID

select @@FETCH_STATUS

select @@LANGID

select @@LANGUAGE

select @@CPU_BUSY

select @@CONNECTIONS 

select @@IDLE

SELECT CURRENT_TIMESTAMP
-- GET_TRANSMISSION_STATUS
SELECT GETDATE()
SELECT GETUTCDATE()
SELECT @@CONNECTIONS
SELECT @@CPU_BUSY
SELECT @@DBTS
SELECT @@IDLE
SELECT @@IO_BUSY
SELECT @@MAX_CONNECTIONS
SELECT @@PACK_RECEIVED
SELECT @@PACK_SENT
SELECT @@PACKET_ERRORS
SELECT @@TIMETICKS
SELECT @@TOTAL_ERRORS
SELECT @@TOTAL_READ
SELECT @@TOTAL_WRITE
