
-- SELECT TABLESPACE_NAME
--   FROM DBA_TABLESPACES
--  WHERE TABLESPACE_NAME = 'USERS';

--  alter session set CONTAINER = FREEPDB1;


--  ALTER USER C##ViV QUOTA UNLIMITED ON USERS;


--  SELECT TABLESPACE_NAME
--   FROM DBA_TABLESPACES
--  WHERE TABLESPACE_NAME = 'USERS';

--  SELECT TABLESPACE_NAME
--   FROM DBA_TABLESPACES;

-- SELECT SYS_CONTEXT('USERENV', 'CON_NAME') AS CURRENT_CONTAINER
-- FROM DUAL;

-- -- USERS 테이블스페이스가 존재하는지 확인
-- SELECT TABLESPACE_NAME
--   FROM DBA_TABLESPACES
--  WHERE TABLESPACE_NAME = 'USERS';


--  SELECT tablespace_name FROM dba_tablespaces;

-- ALTER USER C##ViV DEFAULT TABLESPACE SYSAUX;

-- ALTER USER C##ViV QUOTA UNLIMITED ON SYSAUX;

-- SELECT * FROM DBA_TS_QUOTAS WHERE TABLESPACE_NAME = 'SYSAUX' AND USERNAME = 'C##ViV';

-- SELECT TABLESPACE_NAME, STATUS FROM DBA_TABLESPACES WHERE TABLESPACE_NAME = 'SYSAUX';


-- SELECT SID, SERIAL#, USERNAME, STATUS, MACHINE, PROGRAM
-- FROM V$SESSION
-- WHERE USERNAME = 'C##VIV';


-- SELECT SID, SERIAL#, USERNAME, STATUS, MACHINE, PROGRAM
-- FROM V$SESSION;




CREATE TABLESPACE USERS
DATAFILE 'users01.dbf'
SIZE 50M
AUTOEXTEND ON
NEXT 50M MAXSIZE UNLIMITED;


ALTER USER C##ViV QUOTA UNLIMITED ON USERS;

SELECT TABLESPACE_NAME
  FROM DBA_TABLESPACES
 WHERE TABLESPACE_NAME = 'USERS';


 ALTER SESSION SET CONTAINER = FREEPDB1;


--  ALTER USER C##ViV SET CONTAINER_DATA = ALL CONTAINERS;


--  ALTER USER C##ViV QUOTA UNLIMITED ON USERS;

--  ALTER USER C##ViV QUOTA UNLIMITED ON USERS;

 SELECT USERNAME, DEFAULT_TABLESPACE, TEMPORARY_TABLESPACE
FROM DBA_USERS
WHERE USERNAME = 'C##VIV';

ALTER USER C##ViV DEFAULT TABLESPACE USERS;